
import { OxfordWord } from './types';

export const INITIAL_WORDS: OxfordWord[] = [
  // === A1 LEVEL (Beginner) ===
  { word: "a", level: "A1", translation: "หนึ่ง (คำนำหน้านาม)", phonetic: "/ə/", posEn: "det.", posTh: "คำนำหน้านาม" },
  { word: "about", level: "A1", translation: "เกี่ยวกับ", phonetic: "/əˈbaʊt/", posEn: "prep., adv.", posTh: "บุพบท/วิเศษณ์" },
  { word: "above", level: "A1", translation: "เหนือ/ข้างบน", phonetic: "/əˈbʌv/", posEn: "prep., adv.", posTh: "บุพบท/วิเศษณ์" },
  { word: "across", level: "A1", translation: "ข้าม/อีกฝั่ง", phonetic: "/əˈkrɒs/", posEn: "prep., adv.", posTh: "บุพบท/วิเศษณ์" },
  { word: "action", level: "A1", translation: "การกระทำ", phonetic: "/ˈækʃn/", posEn: "n.", posTh: "นาม" },
  { word: "activity", level: "A1", translation: "กิจกรรม", phonetic: "/ækˈtɪvəti/", posEn: "n.", posTh: "นาม" },
  { word: "actor", level: "A1", translation: "นักแสดงชาย", phonetic: "/ˈæktə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "actress", level: "A1", translation: "นักแสดงหญิง", phonetic: "/ˈæktrəs/", posEn: "n.", posTh: "นาม" },
  { word: "add", level: "A1", translation: "เพิ่ม", phonetic: "/æd/", posEn: "v.", posTh: "กริยา" },
  { word: "address", level: "A1", translation: "ที่อยู่", phonetic: "/əˈdres/", posEn: "n.", posTh: "นาม" },
  { word: "adult", level: "A1", translation: "ผู้ใหญ่", phonetic: "/ˈædʌlt/", posEn: "n.", posTh: "นาม" },
  { word: "advice", level: "A1", translation: "คำแนะนำ", phonetic: "/ədˈvaɪs/", posEn: "n.", posTh: "นาม" },
  { word: "afraid", level: "A1", translation: "กลัว", phonetic: "/əˈfreɪd/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "after", level: "A1", translation: "หลังจาก", phonetic: "/ˈɑːftə(r)/", posEn: "prep.", posTh: "บุพบท" },
  { word: "afternoon", level: "A1", translation: "ตอนบ่าย", phonetic: "/ˌɑːftəˈnuːn/", posEn: "n.", posTh: "นาม" },
  { word: "again", level: "A1", translation: "อีกครั้ง", phonetic: "/əˈɡen/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "age", level: "A1", translation: "อายุ", phonetic: "/eɪdʒ/", posEn: "n.", posTh: "นาม" },
  { word: "ago", level: "A1", translation: "ที่ผ่านมาแล้ว", phonetic: "/əˈɡəʊ/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "agree", level: "A1", translation: "เห็นด้วย", phonetic: "/əˈɡriː/", posEn: "v.", posTh: "กริยา" },
  { word: "air", level: "A1", translation: "อากาศ", phonetic: "/eə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "airport", level: "A1", translation: "สนามบิน", phonetic: "/ˈeəpɔːt/", posEn: "n.", posTh: "นาม" },
  { word: "all", level: "A1", translation: "ทั้งหมด", phonetic: "/ɔːl/", posEn: "det., pron.", posTh: "คำนำหน้านาม/สรรพนาม" },
  { word: "also", level: "A1", translation: "เช่นกัน/ด้วย", phonetic: "/ˈɔːlsəʊ/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "always", level: "A1", translation: "เสมอ", phonetic: "/ˈɔːlweɪz/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "amazing", level: "A1", translation: "น่าอัศจรรย์", phonetic: "/əˈmeɪzɪŋ/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "angry", level: "A1", translation: "โกรธ", phonetic: "/ˈæŋɡri/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "animal", level: "A1", translation: "สัตว์", phonetic: "/ˈænɪml/", posEn: "n.", posTh: "นาม" },
  { word: "another", level: "A1", translation: "อีกอันหนึ่ง", phonetic: "/əˈnʌðə(r)/", posEn: "det./pron.", posTh: "คำนำหน้านาม/สรรพนาม" },
  { word: "answer", level: "A1", translation: "คำตอบ/ตอบ", phonetic: "/ˈɑːnsə(r)/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "any", level: "A1", translation: "บ้าง/ใดๆ", phonetic: "/ˈeni/", posEn: "det., pron.", posTh: "คำนำหน้านาม/สรรพนาม" },
  { word: "anyone", level: "A1", translation: "ใครก็ตาม", phonetic: "/ˈeniwʌn/", posEn: "pron.", posTh: "สรรพนาม" },
  { word: "anything", level: "A1", translation: "อะไรก็ตาม", phonetic: "/ˈeniθɪŋ/", posEn: "pron.", posTh: "สรรพนาม" },
  { word: "apartment", level: "A1", translation: "อพาร์ตเมนต์", phonetic: "/əˈpɑːtmənt/", posEn: "n.", posTh: "นาม" },
  { word: "apple", level: "A1", translation: "แอปเปิ้ล", phonetic: "/ˈæpl/", posEn: "n.", posTh: "นาม" },
  { word: "area", level: "A1", translation: "พื้นที่", phonetic: "/ˈeəriə/", posEn: "n.", posTh: "นาม" },
  { word: "arm", level: "A1", translation: "แขน", phonetic: "/ɑːm/", posEn: "n.", posTh: "นาม" },
  { word: "around", level: "A1", translation: "รอบๆ", phonetic: "/əˈraʊnd/", posEn: "prep., adv.", posTh: "บุพบท/วิเศษณ์" },
  { word: "arrive", level: "A1", translation: "มาถึง", phonetic: "/əˈraɪv/", posEn: "v.", posTh: "กริยา" },
  { word: "art", level: "A1", translation: "ศิลปะ", phonetic: "/ɑːt/", posEn: "n.", posTh: "นาม" },
  { word: "article", level: "A1", translation: "บทความ/สิ่งของ", phonetic: "/ˈɑːtɪkl/", posEn: "n.", posTh: "นาม" },
  { word: "artist", level: "A1", translation: "ศิลปิน", phonetic: "/ˈɑːtɪst/", posEn: "n.", posTh: "นาม" },
  { word: "ask", level: "A1", translation: "ถาม/ขอ", phonetic: "/ɑːsk/", posEn: "v.", posTh: "กริยา" },
  { word: "at", level: "A1", translation: "ที่", phonetic: "/æt/", posEn: "prep.", posTh: "บุพบท" },
  { word: "aunt", level: "A1", translation: "ป้า/น้า/อา (หญิง)", phonetic: "/ɑːnt/", posEn: "n.", posTh: "นาม" },
  { word: "away", level: "A1", translation: "ไปที่อื่น/ห่างออกไป", phonetic: "/əˈweɪ/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "baby", level: "A1", translation: "ทารก", phonetic: "/ˈbeɪbi/", posEn: "n.", posTh: "นาม" },
  { word: "back", level: "A1", translation: "หลัง/กลับ", phonetic: "/bæk/", posEn: "n., adv.", posTh: "นาม/วิเศษณ์" },
  { word: "bad", level: "A1", translation: "แย่", phonetic: "/bæd/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "bag", level: "A1", translation: "กระเป๋า", phonetic: "/bæɡ/", posEn: "n.", posTh: "นาม" },
  { word: "ball", level: "A1", translation: "ลูกบอล", phonetic: "/bɔːl/", posEn: "n.", posTh: "นาม" },
  { word: "banana", level: "A1", translation: "กล้วย", phonetic: "/bəˈnɑːnə/", posEn: "n.", posTh: "นาม" },
  { word: "bank", level: "A1", translation: "ธนาคาร", phonetic: "/bæŋk/", posEn: "n.", posTh: "นาม" },
  { word: "bath", level: "A1", translation: "การอาบน้ำ", phonetic: "/bɑːθ/", posEn: "n.", posTh: "นาม" },
  { word: "bathroom", level: "A1", translation: "ห้องน้ำ", phonetic: "/ˈbɑːθruːm/", posEn: "n.", posTh: "นาม" },
  { word: "be", level: "A1", translation: "เป็น/อยู่/คือ", phonetic: "/biː/", posEn: "v.", posTh: "กริยา" },
  { word: "beach", level: "A1", translation: "ชายหาด", phonetic: "/biːtʃ/", posEn: "n.", posTh: "นาม" },
  { word: "beautiful", level: "A1", translation: "สวยงาม", phonetic: "/ˈbjuːtɪfl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "because", level: "A1", translation: "เพราะว่า", phonetic: "/bɪˈkɒz/", posEn: "conj.", posTh: "สันธาน" },
  { word: "become", level: "A1", translation: "กลายเป็น", phonetic: "/bɪˈkʌm/", posEn: "v.", posTh: "กริยา" },
  { word: "bed", level: "A1", translation: "เตียง", phonetic: "/bed/", posEn: "n.", posTh: "นาม" },
  { word: "bedroom", level: "A1", translation: "ห้องนอน", phonetic: "/ˈbedruːm/", posEn: "n.", posTh: "นาม" },
  { word: "beer", level: "A1", translation: "เบียร์", phonetic: "/bɪə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "before", level: "A1", translation: "ก่อน", phonetic: "/bɪˈfɔː(r)/", posEn: "prep.", posTh: "บุพบท" },
  { word: "begin", level: "A1", translation: "เริ่มต้น", phonetic: "/bɪˈɡɪn/", posEn: "v.", posTh: "กริยา" },
  { word: "beginning", level: "A1", translation: "จุดเริ่มต้น", phonetic: "/bɪˈɡɪnɪŋ/", posEn: "n.", posTh: "นาม" },
  { word: "behind", level: "A1", translation: "ข้างหลัง", phonetic: "/bɪˈhaɪnd/", posEn: "prep., adv.", posTh: "บุพบท/วิเศษณ์" },
  { word: "believe", level: "A1", translation: "เชื่อ", phonetic: "/bɪˈliːv/", posEn: "v.", posTh: "กริยา" },
  { word: "below", level: "A1", translation: "ข้างล่าง", phonetic: "/bɪˈləʊ/", posEn: "adv., prep.", posTh: "วิเศษณ์/บุพบท" },
  { word: "best", level: "A1", translation: "ดีที่สุด", phonetic: "/best/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "better", level: "A1", translation: "ดีกว่า", phonetic: "/ˈbetə(r)/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "between", level: "A1", translation: "ระหว่าง", phonetic: "/bɪˈtwiːn/", posEn: "prep.", posTh: "บุพบท" },
  { word: "big", level: "A1", translation: "ใหญ่", phonetic: "/bɪɡ/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "bike", level: "A1", translation: "จักรยาน", phonetic: "/baɪk/", posEn: "n.", posTh: "นาม" },
  { word: "bird", level: "A1", translation: "นก", phonetic: "/bɜːd/", posEn: "n.", posTh: "นาม" },
  { word: "birthday", level: "A1", translation: "วันเกิด", phonetic: "/ˈbɜːθdeɪ/", posEn: "n.", posTh: "นาม" },
  { word: "black", level: "A1", translation: "สีดำ", phonetic: "/blæk/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "blue", level: "A1", translation: "สีฟ้า/น้ำเงิน", phonetic: "/bluː/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "boat", level: "A1", translation: "เรือ", phonetic: "/bəʊt/", posEn: "n.", posTh: "นาม" },
  { word: "body", level: "A1", translation: "ร่างกาย", phonetic: "/ˈbɒdi/", posEn: "n.", posTh: "นาม" },
  { word: "book", level: "A1", translation: "หนังสือ", phonetic: "/bʊk/", posEn: "n.", posTh: "นาม" },
  { word: "box", level: "A1", translation: "กล่อง", phonetic: "/bɒks/", posEn: "n.", posTh: "นาม" },
  { word: "boy", level: "A1", translation: "เด็กผู้ชาย", phonetic: "/bɔɪ/", posEn: "n.", posTh: "นาม" },
  { word: "bread", level: "A1", translation: "ขนมปัง", phonetic: "/bred/", posEn: "n.", posTh: "นาม" },
  { word: "breakfast", level: "A1", translation: "อาหารเช้า", phonetic: "/ˈbrekfəst/", posEn: "n.", posTh: "นาม" },
  { word: "bring", level: "A1", translation: "นำมา", phonetic: "/brɪŋ/", posEn: "v.", posTh: "กริยา" },
  { word: "brother", level: "A1", translation: "พี่ชาย/น้องชาย", phonetic: "/ˈbrʌðə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "brown", level: "A1", translation: "สีน้ำตาล", phonetic: "/braʊn/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "build", level: "A1", translation: "สร้าง", phonetic: "/bɪld/", posEn: "v.", posTh: "กริยา" },
  { word: "building", level: "A1", translation: "ตึก/อาคาร", phonetic: "/ˈbɪldɪŋ/", posEn: "n.", posTh: "นาม" },
  { word: "bus", level: "A1", translation: "รถเมล์", phonetic: "/bʌs/", posEn: "n.", posTh: "นาม" },
  { word: "business", level: "A1", translation: "ธุรกิจ", phonetic: "/ˈbɪznəs/", posEn: "n.", posTh: "นาม" },
  { word: "busy", level: "A1", translation: "ยุ่ง", phonetic: "/ˈbɪzi/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "buy", level: "A1", translation: "ซื้อ", phonetic: "/baɪ/", posEn: "v.", posTh: "กริยา" },
  { word: "by", level: "A1", translation: "โดย/ข้างๆ", phonetic: "/baɪ/", posEn: "prep.", posTh: "บุพบท" },
  { word: "cake", level: "A1", translation: "เค้ก", phonetic: "/keɪk/", posEn: "n.", posTh: "นาม" },
  { word: "call", level: "A1", translation: "เรียก/โทร", phonetic: "/kɔːl/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "camera", level: "A1", translation: "กล้อง", phonetic: "/ˈkæmrə/", posEn: "n.", posTh: "นาม" },
  { word: "car", level: "A1", translation: "รถยนต์", phonetic: "/kɑː(r)/", posEn: "n.", posTh: "นาม" },
  { word: "card", level: "A1", translation: "การ์ด/บัตร", phonetic: "/kɑːd/", posEn: "n.", posTh: "นาม" },
  { word: "cat", level: "A1", translation: "แมว", phonetic: "/kæt/", posEn: "n.", posTh: "นาม" },
  { word: "chair", level: "A1", translation: "เก้าอี้", phonetic: "/tʃeə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "cheap", level: "A1", translation: "ถูก", phonetic: "/tʃiːp/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "cheese", level: "A1", translation: "ชีส", phonetic: "/tʃiːz/", posEn: "n.", posTh: "นาม" },
  { word: "chicken", level: "A1", translation: "ไก่", phonetic: "/ˈtʃɪkɪn/", posEn: "n.", posTh: "นาม" },
  { word: "child", level: "A1", translation: "เด็ก", phonetic: "/tʃaɪld/", posEn: "n.", posTh: "นาม" },
  { word: "chocolate", level: "A1", translation: "ช็อกโกแลต", phonetic: "/ˈtʃɒklət/", posEn: "n.", posTh: "นาม" },
  { word: "choose", level: "A1", translation: "เลือก", phonetic: "/tʃuːz/", posEn: "v.", posTh: "กริยา" },
  { word: "city", level: "A1", translation: "เมือง", phonetic: "/ˈsɪti/", posEn: "n.", posTh: "นาม" },
  { word: "class", level: "A1", translation: "ชั้นเรียน", phonetic: "/klɑːs/", posEn: "n.", posTh: "นาม" },
  { word: "clean", level: "A1", translation: "สะอาด/ทำความสะอาด", phonetic: "/kliːn/", posEn: "adj., v.", posTh: "คุณศัพท์/กริยา" },
  { word: "climb", level: "A1", translation: "ปีน", phonetic: "/klaɪm/", posEn: "v.", posTh: "กริยา" },
  { word: "coffee", level: "A1", translation: "กาแฟ", phonetic: "/ˈkɒfi/", posEn: "n.", posTh: "นาม" },
  { word: "cold", level: "A1", translation: "หนาว/เย็น", phonetic: "/kəʊld/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "come", level: "A1", translation: "มา", phonetic: "/kʌm/", posEn: "v.", posTh: "กริยา" },
  { word: "cook", level: "A1", translation: "ทำอาหาร", phonetic: "/kʊk/", posEn: "v.", posTh: "กริยา" },
  { word: "correct", level: "A1", translation: "ถูกต้อง", phonetic: "/kəˈrekt/", posEn: "adj., v.", posTh: "คุณศัพท์/กริยา" },
  { word: "country", level: "A1", translation: "ประเทศ", phonetic: "/ˈkʌntri/", posEn: "n.", posTh: "นาม" },
  { word: "dance", level: "A1", translation: "เต้น", phonetic: "/dɑːns/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "day", level: "A1", translation: "วัน", phonetic: "/deɪ/", posEn: "n.", posTh: "นาม" },
  { word: "decide", level: "A1", translation: "ตัดสินใจ", phonetic: "/dɪˈsaɪd/", posEn: "v.", posTh: "กริยา" },
  { word: "delicious", level: "A1", translation: "อร่อย", phonetic: "/dɪˈlɪʃəs/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "do", level: "A1", translation: "ทำ", phonetic: "/duː/", posEn: "v.", posTh: "กริยา" },
  { word: "dog", level: "A1", translation: "สุนัข", phonetic: "/dɒɡ/", posEn: "n.", posTh: "นาม" },
  { word: "door", level: "A1", translation: "ประตู", phonetic: "/dɔː(r)/", posEn: "n.", posTh: "นาม" },
  { word: "drink", level: "A1", translation: "ดื่ม/เครื่องดื่ม", phonetic: "/drɪŋk/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "eat", level: "A1", translation: "กิน", phonetic: "/iːt/", posEn: "v.", posTh: "กริยา" },
  { word: "egg", level: "A1", translation: "ไข่", phonetic: "/eɡ/", posEn: "n.", posTh: "นาม" },
  { word: "every", level: "A1", translation: "ทุกๆ", phonetic: "/ˈevri/", posEn: "det.", posTh: "คำนำหน้านาม" },
  { word: "family", level: "A1", translation: "ครอบครัว", phonetic: "/ˈfæməli/", posEn: "n., adj.", posTh: "นาม/คุณศัพท์" },
  { word: "father", level: "A1", translation: "พ่อ", phonetic: "/ˈfɑːðə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "find", level: "A1", translation: "หา/พบ", phonetic: "/faɪnd/", posEn: "v.", posTh: "กริยา" },
  { word: "food", level: "A1", translation: "อาหาร", phonetic: "/fuːd/", posEn: "n.", posTh: "นาม" },
  { word: "friend", level: "A1", translation: "เพื่อน", phonetic: "/frend/", posEn: "n.", posTh: "นาม" },
  { word: "get", level: "A1", translation: "ได้รับ/ไปเอา", phonetic: "/ɡet/", posEn: "v.", posTh: "กริยา" },
  { word: "go", level: "A1", translation: "ไป", phonetic: "/ɡəʊ/", posEn: "v.", posTh: "กริยา" },
  { word: "good", level: "A1", translation: "ดี", phonetic: "/ɡʊd/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "happy", level: "A1", translation: "มีความสุข", phonetic: "/ˈhæpi/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "home", level: "A1", translation: "บ้าน", phonetic: "/həʊm/", posEn: "n., adv.", posTh: "นาม/วิเศษณ์" },
  { word: "house", level: "A1", translation: "บ้าน", phonetic: "/haʊs/", posEn: "n.", posTh: "นาม" },
  { word: "know", level: "A1", translation: "รู้/รู้จัก", phonetic: "/nəʊ/", posEn: "v.", posTh: "กริยา" },
  { word: "learn", level: "A1", translation: "เรียนรู้", phonetic: "/lɜːn/", posEn: "v.", posTh: "กริยา" },
  { word: "love", level: "A1", translation: "รัก", phonetic: "/lʌv/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "man", level: "A1", translation: "ผู้ชาย", phonetic: "/mæn/", posEn: "n.", posTh: "นาม" },
  { word: "mother", level: "A1", translation: "แม่", phonetic: "/ˈmʌðə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "new", level: "A1", translation: "ใหม่", phonetic: "/njuː/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "night", level: "A1", translation: "กลางคืน", phonetic: "/naɪt/", posEn: "n.", posTh: "นาม" },
  { word: "old", level: "A1", translation: "เก่า/แก่", phonetic: "/əʊld/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "people", level: "A1", translation: "คน/ประชาชน", phonetic: "/ˈpiːpl/", posEn: "n.", posTh: "นาม" },
  { word: "place", level: "A1", translation: "สถานที่", phonetic: "/pleɪs/", posEn: "n.", posTh: "นาม" },
  { word: "read", level: "A1", translation: "อ่าน", phonetic: "/riːd/", posEn: "v.", posTh: "กริยา" },
  { word: "school", level: "A1", translation: "โรงเรียน", phonetic: "/skuːl/", posEn: "n.", posTh: "นาม" },
  { word: "see", level: "A1", translation: "เห็น", phonetic: "/siː/", posEn: "v.", posTh: "กริยา" },
  { word: "student", level: "A1", translation: "นักเรียน", phonetic: "/ˈstjuːdnt/", posEn: "n.", posTh: "นาม" },
  { word: "teacher", level: "A1", translation: "ครู", phonetic: "/ˈtiːtʃə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "time", level: "A1", translation: "เวลา", phonetic: "/taɪm/", posEn: "n.", posTh: "นาม" },
  { word: "water", level: "A1", translation: "น้ำ", phonetic: "/ˈwɔːtə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "work", level: "A1", translation: "งาน/ทำงาน", phonetic: "/wɜːk/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "write", level: "A1", translation: "เขียน", phonetic: "/raɪt/", posEn: "v.", posTh: "กริยา" },

  // === A2 LEVEL (Elementary) ===
  { word: "ability", level: "A2", translation: "ความสามารถ", phonetic: "/əˈbɪləti/", posEn: "n.", posTh: "นาม" },
  { word: "able", level: "A2", translation: "สามารถ", phonetic: "/ˈeɪbl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "abroad", level: "A2", translation: "ต่างประเทศ", phonetic: "/əˈbrɔːd/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "accept", level: "A2", translation: "ยอมรับ", phonetic: "/əkˈsept/", posEn: "v.", posTh: "กริยา" },
  { word: "accident", level: "A2", translation: "อุบัติเหตุ", phonetic: "/ˈæksɪdənt/", posEn: "n.", posTh: "นาม" },
  { word: "achieve", level: "A2", translation: "บรรลุผลสำเร็จ", phonetic: "/əˈtʃiːv/", posEn: "v.", posTh: "กริยา" },
  { word: "act", level: "A2", translation: "แสดง/กระทำ", phonetic: "/ækt/", posEn: "v.", posTh: "กริยา" },
  { word: "active", level: "A2", translation: "คล่องแคล่ว/กระตือรือร้น", phonetic: "/ˈæktɪv/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "actually", level: "A2", translation: "จริงๆ แล้ว", phonetic: "/ˈæktʃuəli/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "advantage", level: "A2", translation: "ข้อได้เปรียบ", phonetic: "/ədˈvɑːntɪdʒ/", posEn: "n.", posTh: "นาม" },
  { word: "adventure", level: "A2", translation: "การผจญภัย", phonetic: "/ədˈventʃə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "advertise", level: "A2", translation: "โฆษณา", phonetic: "/ˈædvətaɪz/", posEn: "v.", posTh: "กริยา" },
  { word: "affect", level: "A2", translation: "ส่งผลกระทบ", phonetic: "/əˈfekt/", posEn: "v.", posTh: "กริยา" },
  { word: "against", level: "A2", translation: "ต่อต้าน/ตรงข้ามกับ", phonetic: "/əˈɡenst/", posEn: "prep.", posTh: "บุพบท" },
  { word: "airline", level: "A2", translation: "สายการบิน", phonetic: "/ˈeəlaɪn/", posEn: "n.", posTh: "นาม" },
  { word: "alive", level: "A2", translation: "มีชีวิตอยู่", phonetic: "/əˈlaɪv/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "allow", level: "A2", translation: "อนุญาต", phonetic: "/əˈlaʊ/", posEn: "v.", posTh: "กริยา" },
  { word: "almost", level: "A2", translation: "เกือบจะ", phonetic: "/ˈɔːlməʊst/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "alone", level: "A2", translation: "ลำพัง/คนเดียว", phonetic: "/əˈləʊn/", posEn: "adj./adv.", posTh: "คุณศัพท์/วิเศษณ์" },
  { word: "along", level: "A2", translation: "ตามทาง/ยาวไปตาม", phonetic: "/əˈlɒŋ/", posEn: "prep., adv.", posTh: "บุพบท/วิเศษณ์" },
  { word: "already", level: "A2", translation: "เรียบร้อยแล้ว", phonetic: "/ɔːlˈredi/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "alternative", level: "A2", translation: "ทางเลือก", phonetic: "/ɔːlˈtɜːnətɪv/", posEn: "n.", posTh: "นาม" },
  { word: "although", level: "A2", translation: "ถึงแม้ว่า", phonetic: "/ɔːlˈðəʊ/", posEn: "conj.", posTh: "สันธาน" },
  { word: "among", level: "A2", translation: "ในหมู่/ท่ามกลาง", phonetic: "/əˈmʌŋ/", posEn: "prep.", posTh: "บุพบท" },
  { word: "amount", level: "A2", translation: "จำนวน", phonetic: "/əˈmaʊnt/", posEn: "n.", posTh: "นาม" },
  { word: "ancient", level: "A2", translation: "โบราณ", phonetic: "/ˈeɪnʃənt/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "ankle", level: "A2", translation: "ข้อเท้า", phonetic: "/ˈæŋkl/", posEn: "n.", posTh: "นาม" },
  { word: "anybody", level: "A2", translation: "ใครก็ตาม", phonetic: "/ˈenibɒdi/", posEn: "pron.", posTh: "สรรพนาม" },
  { word: "anyway", level: "A2", translation: "อย่างไรก็ตาม", phonetic: "/ˈeniweɪ/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "anywhere", level: "A2", translation: "ที่ไหนก็ได้", phonetic: "/ˈeniweə(r)/", posEn: "adv., pron.", posTh: "วิเศษณ์/สรรพนาม" },
  { word: "appear", level: "A2", translation: "ปรากฏตัว", phonetic: "/əˈpɪə(r)/", posEn: "v.", posTh: "กริยา" },
  { word: "appearance", level: "A2", translation: "รูปลักษณ์", phonetic: "/əˈpɪərəns/", posEn: "n.", posTh: "นาม" },
  { word: "apply", level: "A2", translation: "สมัคร/ประยุกต์ใช้", phonetic: "/əˈplaɪ/", posEn: "v.", posTh: "กริยา" },
  { word: "architect", level: "A2", translation: "สถาปนิก", phonetic: "/ˈɑːkɪtekt/", posEn: "n.", posTh: "นาม" },
  { word: "army", level: "A2", translation: "กองทัพ", phonetic: "/ˈɑːmi/", posEn: "n.", posTh: "นาม" },
  { word: "arrange", level: "A2", translation: "จัดการ/จัดเตรียม", phonetic: "/əˈreɪndʒ/", posEn: "v.", posTh: "กริยา" },
  { word: "asleep", level: "A2", translation: "หลับ", phonetic: "/əˈsliːp/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "assistant", level: "A2", translation: "ผู้ช่วย", phonetic: "/əˈsɪstənt/", posEn: "n., adj.", posTh: "นาม/คุณศัพท์" },
  { word: "athlete", level: "A2", translation: "นักกีฬา", phonetic: "/ˈæθliːt/", posEn: "n.", posTh: "นาม" },
  { word: "attack", level: "A2", translation: "โจมตี", phonetic: "/əˈtæk/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "attend", level: "A2", translation: "เข้าร่วม", phonetic: "/əˈtend/", posEn: "v.", posTh: "กริยา" },
  { word: "audience", level: "A2", translation: "ผู้ชม", phonetic: "/ˈɔːdiəns/", posEn: "n.", posTh: "นาม" },
  { word: "author", level: "A2", translation: "ผู้เขียน/นักประพันธ์", phonetic: "/ˈɔːθə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "available", level: "A2", translation: "ที่มีอยู่/พร้อมใช้", phonetic: "/əˈveɪləbl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "average", level: "A2", translation: "เฉลี่ย", phonetic: "/ˈævərɪdʒ/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "avoid", level: "A2", translation: "หลีกเลี่ยง", phonetic: "/əˈvɔɪd/", posEn: "v.", posTh: "กริยา" },
  { word: "award", level: "A2", translation: "รางวัล", phonetic: "/əˈwɔːd/", posEn: "n.", posTh: "นาม" },
  { word: "awful", level: "A2", translation: "แย่มาก/น่ากลัว", phonetic: "/ˈɔːfl/", posEn: "adj.", posTh: "คุณศัพท์" },

  // === B1 LEVEL (Intermediate) ===
  { word: "absolutely", level: "B1", translation: "อย่างแน่นอน/อย่างสิ้นเชิง", phonetic: "/ˈæbsəluːtli/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "academic", level: "B1", translation: "ทางวิชาการ", phonetic: "/ˌækəˈdemɪk/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "access", level: "B1", translation: "การเข้าถึง", phonetic: "/ˈækses/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "accommodation", level: "B1", translation: "ที่พักอาศัย", phonetic: "/əˌkɒməˈdeɪʃn/", posEn: "n.", posTh: "นาม" },
  { word: "achievement", level: "B1", translation: "ความสำเร็จ", phonetic: "/əˈtʃiːvmənt/", posEn: "n.", posTh: "นาม" },
  { word: "admire", level: "B1", translation: "ชื่นชม", phonetic: "/ədˈmaɪə(r)/", posEn: "v.", posTh: "กริยา" },
  { word: "admit", level: "B1", translation: "ยอมรับ/สารภาพ", phonetic: "/ədˈmɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "advanced", level: "B1", translation: "ก้าวหน้า/ระดับสูง", phonetic: "/ədˈvɑːnst/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "aim", level: "B1", translation: "เป้าหมาย/เล็ง", phonetic: "/eɪm/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "alarm", level: "B1", translation: "สัญญาณเตือน", phonetic: "/əˈlɑːm/", posEn: "n.", posTh: "นาม" },
  { word: "alcohol", level: "B1", translation: "แอลกอฮอล์", phonetic: "/ˈælkəhɒl/", posEn: "n.", posTh: "นาม" },
  { word: "ambition", level: "B1", translation: "ความทะเยอทะยาน", phonetic: "/æmˈbɪʃn/", posEn: "n.", posTh: "นาม" },
  { word: "analyse", level: "B1", translation: "วิเคราะห์", phonetic: "/ˈænəlaɪz/", posEn: "v.", posTh: "กริยา" },
  { word: "analysis", level: "B1", translation: "การวิเคราะห์", phonetic: "/əˈnæləsɪs/", posEn: "n.", posTh: "นาม" },
  { word: "announce", level: "B1", translation: "ประกาศ", phonetic: "/əˈnaʊns/", posEn: "v.", posTh: "กริยา" },
  { word: "announcement", level: "B1", translation: "การประกาศ", phonetic: "/əˈnaʊnsmənt/", posEn: "n.", posTh: "นาม" },
  { word: "annoy", level: "B1", translation: "ทำให้รำคาญ", phonetic: "/əˈnɔɪ/", posEn: "v.", posTh: "กริยา" },
  { word: "apologize", level: "B1", translation: "ขอโทษ", phonetic: "/əˈpɒlədʒaɪz/", posEn: "v.", posTh: "กริยา" },
  { word: "application", level: "B1", translation: "การสมัคร/แอปพลิเคชัน", phonetic: "/ˌæplɪˈkeɪʃn/", posEn: "n.", posTh: "นาม" },
  { word: "appointment", level: "B1", translation: "การนัดหมาย", phonetic: "/əˈpɔɪntmənt/", posEn: "n.", posTh: "นาม" },
  { word: "appreciate", level: "B1", translation: "ซาบซึ้ง/เห็นคุณค่า", phonetic: "/əˈpriːʃieɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "approximately", level: "B1", translation: "โดยประมาณ", phonetic: "/əˈprɒksɪmətli/", posEn: "adv.", posTh: "วิเศษณ์" },
  { word: "arrest", level: "B1", translation: "จับกุม", phonetic: "/əˈrest/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "arrival", level: "B1", translation: "การมาถึง", phonetic: "/əˈraɪvl/", posEn: "n.", posTh: "นาม" },
  { word: "assignment", level: "B1", translation: "งานที่ได้รับมอบหมาย", phonetic: "/əˈsaɪnmənt/", posEn: "n.", posTh: "นาม" },
  { word: "assist", level: "B1", translation: "ช่วยเหลือ", phonetic: "/əˈsɪst/", posEn: "v.", posTh: "กริยา" },
  { word: "atmosphere", level: "B1", translation: "บรรยากาศ", phonetic: "/ˈætməsfɪə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "attach", level: "B1", translation: "แนบ/ติด", phonetic: "/əˈtætʃ/", posEn: "v.", posTh: "กริยา" },
  { word: "attitude", level: "B1", translation: "ทัศนคติ", phonetic: "/ˈætɪtjuːd/", posEn: "n.", posTh: "นาม" },
  { word: "attract", level: "B1", translation: "ดึงดูดใจ", phonetic: "/əˈtrækt/", posEn: "v.", posTh: "กริยา" },
  { word: "authority", level: "B1", translation: "อำนาจ/เจ้าหน้าที่", phonetic: "/ɔːˈθɒrəti/", posEn: "n.", posTh: "นาม" },
  { word: "aware", level: "B1", translation: "ตระหนักถึง/รู้ตัว", phonetic: "/əˈweə(r)/", posEn: "adj.", posTh: "คุณศัพท์" },

  // === B2 LEVEL (Upper Intermediate) ===
  { word: "abandon", level: "B2", translation: "ละทิ้ง", phonetic: "/əˈbændən/", posEn: "v.", posTh: "กริยา" },
  { word: "absolute", level: "B2", translation: "สมบูรณ์/แน่นอน", phonetic: "/ˈæbsəluːt/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "acceptable", level: "B2", translation: "เป็นที่ยอมรับได้", phonetic: "/əkˈseptəbl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "accompany", level: "B2", translation: "ไปเป็นเพื่อน/ประกอบกับ", phonetic: "/əˈkʌmpəni/", posEn: "v.", posTh: "กริยา" },
  { word: "accurate", level: "B2", translation: "แม่นยำ/ถูกต้อง", phonetic: "/ˈækjərət/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "accuse", level: "B2", translation: "กล่าวหา", phonetic: "/əˈkjuːz/", posEn: "v.", posTh: "กริยา" },
  { word: "acknowledge", level: "B2", translation: "ยอมรับ/รับทราบ", phonetic: "/əkˈnɒlɪdʒ/", posEn: "v.", posTh: "กริยา" },
  { word: "acquire", level: "B2", translation: "ได้รับมา/เข้าถือครอง", phonetic: "/əˈkwaɪə(r)/", posEn: "v.", posTh: "กริยา" },
  { word: "adapt", level: "B2", translation: "ปรับตัว/ปรับใช้", phonetic: "/əˈdæpt/", posEn: "v.", posTh: "กริยา" },
  { word: "additional", level: "B2", translation: "เพิ่มเติม", phonetic: "/əˈdɪʃənl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "address", level: "B2", translation: "จัดการปัญหา/กล่าวปราศรัย", phonetic: "/əˈdres/", posEn: "v.", posTh: "กริยา" },
  { word: "administration", level: "B2", translation: "การบริหาร", phonetic: "/ədˌmɪnɪˈstreɪʃn/", posEn: "n.", posTh: "นาม" },
  { word: "adopt", level: "B2", translation: "รับมาใช้/รับเลี้ยง", phonetic: "/əˈdɒpt/", posEn: "v.", posTh: "กริยา" },
  { word: "advance", level: "B2", translation: "ความก้าวหน้า/ก้าวหน้า", phonetic: "/ədˈvɑːns/", posEn: "n., v., adj.", posTh: "นาม/กริยา/คุณศัพท์" },
  { word: "affair", level: "B2", translation: "เรื่องราว/กิจการ", phonetic: "/əˈfeə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "agenda", level: "B2", translation: "ระเบียบวาระ", phonetic: "/əˈdʒendə/", posEn: "n.", posTh: "นาม" },
  { word: "aggressive", level: "B2", translation: "ก้าวร้าว/รุกราน", phonetic: "/əˈɡresɪv/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "aid", level: "B2", translation: "ความช่วยเหลือ", phonetic: "/eɪd/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "alter", level: "B2", translation: "เปลี่ยน/แก้ไข", phonetic: "/ˈɔːltə(r)/", posEn: "v.", posTh: "กริยา" },
  { word: "anxious", level: "B2", translation: "วิตกกังวล", phonetic: "/ˈæŋkʃəs/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "apparent", level: "B2", translation: "ชัดแจ้ง/ที่เห็นได้ชัด", phonetic: "/əˈpærənt/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "appeal", level: "B2", translation: "ดึงดูด/อุทธรณ์", phonetic: "/əˈpiːl/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "approach", level: "B2", translation: "วิธีการ/การเข้าใกล้", phonetic: "/əˈprəʊtʃ/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "appropriate", level: "B2", translation: "เหมาะสม", phonetic: "/əˈprəʊpriət/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "approval", level: "B2", translation: "การอนุมัติ/ความเห็นชอบ", phonetic: "/əˈpruːvl/", posEn: "n.", posTh: "นาม" },
  { word: "approve", level: "B2", translation: "อนุมัติ/เห็นชอบ", phonetic: "/əˈpruːv/", posEn: "v.", posTh: "กริยา" },
  { word: "arise", level: "B2", translation: "เกิดขึ้น", phonetic: "/əˈraɪz/", posEn: "v.", posTh: "กริยา" },
  { word: "aspect", level: "B2", translation: "แง่มุม/ลักษณะ", phonetic: "/ˈæspekt/", posEn: "n.", posTh: "นาม" },
  { word: "assess", level: "B2", translation: "ประเมิน", phonetic: "/əˈses/", posEn: "v.", posTh: "กริยา" },
  { word: "assessment", level: "B2", translation: "การประเมิน", phonetic: "/əˈsesmənt/", posEn: "n.", posTh: "นาม" },
  { word: "associate", level: "B2", translation: "เกี่ยวข้อง/คบค้าสมาคม", phonetic: "/əˈsəʊʃieɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "assume", level: "B2", translation: "ทึกทักเอา/สันนิษฐาน", phonetic: "/əˈsjuːm/", posEn: "v.", posTh: "กริยา" },
  { word: "attempt", level: "B2", translation: "พยายาม", phonetic: "/əˈtempt/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "barrier", level: "B2", translation: "อุปสรรค/สิ่งกีดขวาง", phonetic: "/ˈbæriə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "beneficial", level: "B2", translation: "เป็นประโยชน์", phonetic: "/ˌbenɪˈfɪʃl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "bias", level: "B2", translation: "อคติ/ความลำเอียง", phonetic: "/ˈbaɪəs/", posEn: "n.", posTh: "นาม" },
  { word: "boundary", level: "B2", translation: "ขอบเขต/เส้นแบ่งเขต", phonetic: "/ˈbaʊndri/", posEn: "n.", posTh: "นาม" },
  { word: "budget", level: "B2", translation: "งบประมาณ", phonetic: "/ˈbʌdʒɪt/", posEn: "n.", posTh: "นาม" },
  { word: "calculate", level: "B2", translation: "คำนวณ", phonetic: "/ˈkælkjuleɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "capable", level: "B2", translation: "ที่มีความสามารถ", phonetic: "/ˈkeɪpəbl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "capacity", level: "B2", translation: "ความจุ/ขีดความสามารถ", phonetic: "/kəˈpæsəti/", posEn: "n.", posTh: "นาม" },
  { word: "category", level: "B2", translation: "ประเภท/หมวดหมู่", phonetic: "/ˈkætəɡəri/", posEn: "n.", posTh: "นาม" },
  { word: "circumstance", level: "B2", translation: "สถานการณ์/สภาพแวดล้อม", phonetic: "/ˈsɜːkəmstəns/", posEn: "n.", posTh: "นาม" },
  { word: "civil", level: "B2", translation: "เกี่ยวกับพลเมือง/ที่สุภาพ", phonetic: "/ˈsɪvl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "collapse", level: "B2", translation: "พังทลาย/ทรุดตัว", phonetic: "/kəˈlæps/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "commitment", level: "B2", translation: "พันธสัญญา/ความมุ่งมั่น", phonetic: "/kəˈmɪtmənt/", posEn: "n.", posTh: "นาม" },
  { word: "component", level: "B2", translation: "ส่วนประกอบ", phonetic: "/kəmˈpəʊnənt/", posEn: "n.", posTh: "นาม" },
  { word: "concept", level: "B2", translation: "แนวคิด/มโนทัศน์", phonetic: "/ˈkɒnsept/", posEn: "n.", posTh: "นาม" },
  { word: "conduct", level: "B2", translation: "ดำเนินการ/ประพฤติ", phonetic: "/kənˈdʌkt/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "conflict", level: "B2", translation: "ความขัดแย้ง", phonetic: "/ˈkɒnflɪkt/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "consequence", level: "B2", translation: "ผลลัพธ์ที่ตามมา", phonetic: "/ˈkɒnsɪkwəns/", posEn: "n.", posTh: "นาม" },
  { word: "consistent", level: "B2", translation: "สม่ำเสมอ/สอดคล้องกัน", phonetic: "/kənˈsɪstənt/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "constant", level: "B2", translation: "คงที่/สม่ำเสมอ", phonetic: "/ˈkɒnstənt/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "construct", level: "B2", translation: "สร้าง/ก่อสร้าง", phonetic: "/kənˈstrʌkt/", posEn: "v.", posTh: "กริยา" },
  { word: "consult", level: "B2", translation: "ปรึกษา", phonetic: "/kənˈsʌlt/", posEn: "v.", posTh: "กริยา" },
  { word: "consumer", level: "B2", translation: "ผู้บริโภค", phonetic: "/kənˈsjuːmə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "contemporary", level: "B2", translation: "ร่วมสมัย", phonetic: "/kənˈtemprəri/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "context", level: "B2", translation: "บริบท", phonetic: "/ˈkɒntekst/", posEn: "n.", posTh: "นาม" },
  { word: "contribute", level: "B2", translation: "มีส่วนช่วย/สนับสนุน", phonetic: "/kənˈtrɪbjuːt/", posEn: "v.", posTh: "กริยา" },
  { word: "controversial", level: "B2", translation: "ที่อื้อฉาว/ที่ถกเถียงกัน", phonetic: "/ˌkɒntrəˈvɜːʃl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "convinced", level: "B2", translation: "ที่เชื่อมั่น/แน่ใจ", phonetic: "/kənˈvɪnst/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "core", level: "B2", translation: "แกนหลัก/สำคัญที่สุด", phonetic: "/kɔː(r)/", posEn: "n., adj.", posTh: "นาม/คุณศัพท์" },
  { word: "crucial", level: "B2", translation: "สำคัญยิ่งยวด/วิกฤต", phonetic: "/ˈkruːʃl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "currency", level: "B2", translation: "สกุลเงิน/เงินตรา", phonetic: "/ˈkʌrənsi/", posEn: "n.", posTh: "นาม" },
  { word: "debate", level: "B2", translation: "การโต้แย้ง/การถกเถียง", phonetic: "/dɪˈbeɪt/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "decline", level: "B2", translation: "เสื่อมลง/ปฏิเสธ", phonetic: "/dɪˈklaɪn/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "demonstrate", level: "B2", translation: "แสดงให้เห็น/สาธิต", phonetic: "/ˈdemənstreɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "despite", level: "B2", translation: "ทั้งๆ ที่/แม้ว่า", phonetic: "/dɪˈspaɪt/", posEn: "prep.", posTh: "บุพบท" },
  { word: "determine", level: "B2", translation: "กำหนด/ตัดสินใจแน่วแน่", phonetic: "/dɪˈtɜːmɪn/", posEn: "v.", posTh: "กริยา" },
  { word: "distinct", level: "B2", translation: "แตกต่าง/ชัดเจน", phonetic: "/dɪˈstɪŋkt/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "domestic", level: "B2", translation: "ภายในประเทศ/ในครัวเรือน", phonetic: "/dəˈmestɪk/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "dominate", level: "B2", translation: "ครอบงำ/มีอำนาจเหนือ", phonetic: "/ˈdɒmɪneɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "efficient", level: "B2", translation: "ที่มีประสิทธิภาพ", phonetic: "/ɪˈfɪʃnt/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "eliminate", level: "B2", translation: "กำจัด/ตัดออก", phonetic: "/ɪˈlɪmɪneɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "emerge", level: "B2", translation: "ปรากฏออกมา", phonetic: "/ɪˈmɜːdʒ/", posEn: "v.", posTh: "กริยา" },
  { word: "emphasis", level: "B2", translation: "การเน้นย้ำ", phonetic: "/ˈemfəsɪs/", posEn: "n.", posTh: "นาม" },
  { word: "enable", level: "B2", translation: "ทำให้สามารถ", phonetic: "/ɪˈneɪbl/", posEn: "v.", posTh: "กริยา" },
  { word: "enhance", level: "B2", translation: "เสริม/เพิ่มคุณค่า", phonetic: "/ɪnˈhɑːns/", posEn: "v.", posTh: "กริยา" },
  { word: "ensure", level: "B2", translation: "ทำให้มั่นใจ/รับรอง", phonetic: "/ɪnˈʃʊə(r)/", posEn: "v.", posTh: "กริยา" },
  { word: "entire", level: "B2", translation: "ทั้งหมด/ทั้งสิ้น", phonetic: "/ɪnˈtaɪə(r)/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "equivalent", level: "B2", translation: "ที่เท่าเทียมกัน/สิ่งที่มีค่าเท่ากัน", phonetic: "/ɪˈkwɪvələnt/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "establish", level: "B2", translation: "จัดตั้ง/ก่อตั้ง", phonetic: "/ɪˈstæblɪʃ/", posEn: "v.", posTh: "กริยา" },
  { word: "estimate", level: "B2", translation: "ประมาณการ", phonetic: "/ˈestɪmeɪt/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "evaluate", level: "B2", translation: "ประเมินผล", phonetic: "/ɪˈvæljueɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "evidence", level: "B2", translation: "หลักฐาน", phonetic: "/ˈevɪdəns/", posEn: "n.", posTh: "นาม" },
  { word: "exclude", level: "B2", translation: "แยกออกไป/ไม่รวม", phonetic: "/ɪkˈskluːd/", posEn: "v.", posTh: "กริยา" },
  { word: "exposure", level: "B2", translation: "การเปิดเผย/การสัมผัส", phonetic: "/ɪkˈspəʊʒə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "external", level: "B2", translation: "ภายนอก", phonetic: "/ɪkˈstɜːnl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "fundamental", level: "B2", translation: "ที่เป็นพื้นฐาน/สำคัญ", phonetic: "/ˌfʌndəˈmentl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "generate", level: "B2", translation: "สร้าง/ผลิตออกมา", phonetic: "/ˈdʒenəreɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "global", level: "B2", translation: "ระดับโลก/ทั่วโลก", phonetic: "/ˈɡləʊbl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "guarantee", level: "B2", translation: "รับประกัน", phonetic: "/ˌɡærənˈtiː/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "identify", level: "B2", translation: "ระบุตัวตน/พิสูจน์", phonetic: "/aɪˈdentɪfaɪ/", posEn: "v.", posTh: "กริยา" },
  { word: "ignore", level: "B2", translation: "เพิกเฉย/ละเลย", phonetic: "/ɪɡˈnɔː(r)/", posEn: "v.", posTh: "กริยา" },
  { word: "impact", level: "B2", translation: "ผลกระทบ", phonetic: "/ˈɪmpækt/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "implement", level: "B2", translation: "นำไปปฏิบัติ/ทำให้มีผล", phonetic: "/ˈɪmplɪment/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "imply", level: "B2", translation: "บ่งบอก/บอกเป็นนัย", phonetic: "/ɪmˈplaɪ/", posEn: "v.", posTh: "กริยา" },
  { word: "impose", level: "B2", translation: "กำหนด/บังคับใช้", phonetic: "/ɪmˈpəʊz/", posEn: "v.", posTh: "กริยา" },
  { word: "incentive", level: "B2", translation: "สิ่งจูงใจ", phonetic: "/ɪnˈsentɪv/", posEn: "n.", posTh: "นาม" },
  { word: "incorporate", level: "B2", translation: "รวมเข้าด้วยกัน", phonetic: "/ɪnˈkɔːpəreɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "indicate", level: "B2", translation: "บ่งชี้/แสดงให้เห็น", phonetic: "/ˈɪndɪkeɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "individual", level: "B2", translation: "รายบุคคล/เฉพาะราย", phonetic: "/ˌɪndɪˈvɪdʒuəl/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "inevitable", level: "B2", translation: "ซึ่งหลีกเลี่ยงไม่ได้", phonetic: "/ɪnˈevɪtəbl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "influence", level: "B2", translation: "อิทธิพล/มีอิทธิพล", phonetic: "/ˈɪnfluəns/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "infrastructure", level: "B2", translation: "โครงสร้างพื้นฐาน", phonetic: "/ˈɪnfrəstrʌktʃə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "initial", level: "B2", translation: "ในเบื้องต้น/ชื่อย่อ", phonetic: "/ɪˈnɪʃl/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "initiative", level: "B2", translation: "ความคิดริเริ่ม", phonetic: "/ɪˈnɪʃətɪv/", posEn: "n.", posTh: "นาม" },
  { word: "innovation", level: "B2", translation: "นวัตกรรม", phonetic: "/ˌɪnəˈveɪʃn/", posEn: "n.", posTh: "นาม" },
  { word: "insight", level: "B2", translation: "ความเข้าใจลึกซึ้ง", phonetic: "/ˈɪnsaɪt/", posEn: "n.", posTh: "นาม" },
  { word: "install", level: "B2", translation: "ติดตั้ง", phonetic: "/ɪnˈstɔːl/", posEn: "v.", posTh: "กริยา" },
  { word: "institute", level: "B2", translation: "สถาบัน/จัดตั้ง", phonetic: "/ˈɪnstɪtjuːt/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "integrity", level: "B2", translation: "ความซื่อสัตย์/ความสมบูรณ์", phonetic: "/ɪnˈteɡrəti/", posEn: "n.", posTh: "นาม" },
  { word: "internal", level: "B2", translation: "ภายใน", phonetic: "/ɪnˈtɜːnl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "interpret", level: "B2", translation: "ตีความ/แปลความ", phonetic: "/ɪnˈtɜːprət/", posEn: "v.", posTh: "กริยา" },
  { word: "investigate", level: "B2", translation: "สืบสวน/ตรวจสอบ", phonetic: "/ɪnˈvestɪɡeɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "investment", level: "B2", translation: "การลงทุน", phonetic: "/ɪnˈvestmənt/", posEn: "n.", posTh: "นาม" },
  { word: "justify", level: "B2", translation: "อ้างเหตุผล/แสดงให้เห็นความถูกต้อง", phonetic: "/ˈdʒʌstɪfaɪ/", posEn: "v.", posTh: "กริยา" },
  { word: "label", level: "B2", translation: "ฉลาก/ติดป้าย", phonetic: "/ˈleɪbl/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "landscape", level: "B2", translation: "ทิวทัศน์", phonetic: "/ˈlændskeɪp/", posEn: "n.", posTh: "นาม" },
  { word: "maintain", level: "B2", translation: "รักษาไว้/บำรุงรักษา", phonetic: "/meɪnˈteɪn/", posEn: "v.", posTh: "กริยา" },
  { word: "major", level: "B2", translation: "สำคัญ/ส่วนใหญ่", phonetic: "/ˈmeɪdʒə(r)/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "margin", level: "B2", translation: "กำไร/ขอบ", phonetic: "/ˈmɑːdʒɪn/", posEn: "n.", posTh: "นาม" },
  { word: "mechanism", level: "B2", translation: "กลไก", phonetic: "/ˈmekənɪzəm/", posEn: "n.", posTh: "นาม" },
  { word: "modify", level: "B2", translation: "ดัดแปลง/แก้ไข", phonetic: "/ˈmɒdɪfaɪ/", posEn: "v.", posTh: "กริยา" },
  { word: "monitor", level: "B2", translation: "เฝ้าสังเกต/จอภาพ", phonetic: "/ˈmɒnɪtə(r)/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "objective", level: "B2", translation: "เป้าหมาย/เป็นกลาง", phonetic: "/əbˈdʒektɪv/", posEn: "n., adj.", posTh: "นาม/คุณศัพท์" },
  { word: "obtain", level: "B2", translation: "ได้รับ/จัดหามา", phonetic: "/əbˈteɪn/", posEn: "v.", posTh: "กริยา" },
  { word: "obvious", level: "B2", translation: "ชัดเจน/แจ่มแจ้ง", phonetic: "/ˈɒbviəs/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "occupy", level: "B2", translation: "ครอบครอง/อาศัยอยู่", phonetic: "/ˈɒkjupaɪ/", posEn: "v.", posTh: "กริยา" },
  { word: "outcome", level: "B2", translation: "ผลลัพธ์", phonetic: "/ˈaʊtkʌm/", posEn: "n.", posTh: "นาม" },
  { word: "overall", level: "B2", translation: "โดยรวมทั้งหมด", phonetic: "/ˌəʊvərˈɔːl/", posEn: "adj., adv.", posTh: "คุณศัพท์/วิเศษณ์" },
  { word: "parallel", level: "B2", translation: "ขนาน/เทียบเคียง", phonetic: "/ˈpærəlel/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "parameter", level: "B2", translation: "พารามิเตอร์/ตัวแปร", phonetic: "/pəˈræmɪtə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "participate", level: "B2", translation: "มีส่วนร่วม", phonetic: "/pɑːˈtɪsɪpeɪt/", posEn: "v.", posTh: "กริยา" },
  { word: "perception", level: "B2", translation: "การรับรู้/ความเข้าใจ", phonetic: "/pəˈsepʃn/", posEn: "n.", posTh: "นาม" },
  { word: "perspective", level: "B2", translation: "มุมมอง/ทัศนคติ", phonetic: "/pəˈspektɪv/", posEn: "n.", posTh: "นาม" },
  { word: "phase", level: "B2", translation: "ระยะ/ช่วงเวลา", phonetic: "/feɪz/", posEn: "n.", posTh: "นาม" },
  { word: "potential", level: "B2", translation: "ที่มีศักยภาพ/ศักยภาพ", phonetic: "/pəˈtenʃl/", posEn: "adj., n.", posTh: "คุณศัพท์/นาม" },
  { word: "preceding", level: "B2", translation: "ที่มาก่อนหน้านี้", phonetic: "/prɪˈsiːdɪŋ/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "precise", level: "B2", translation: "แม่นยำ/แน่นอน", phonetic: "/prɪˈsaɪs/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "primary", level: "B2", translation: "ขั้นพื้นฐาน/สำคัญที่สุด", phonetic: "/ˈpraɪməri/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "principle", level: "B2", translation: "หลักการ/กฎเกณฑ์", phonetic: "/ˈprɪnsəpl/", posEn: "n.", posTh: "นาม" },
  { word: "prior", level: "B2", translation: "ที่มีมาก่อน/ก่อนหน้า", phonetic: "/ˈpraɪə(r)/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "priority", level: "B2", translation: "ลำดับความสำคัญ", phonetic: "/praɪˈɒrəti/", posEn: "n.", posTh: "นาม" },
  { word: "procedure", level: "B2", translation: "ขั้นตอน/กระบวนการ", phonetic: "/prəˈsiːdʒə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "process", level: "B2", translation: "กระบวนการ/ประมวลผล", phonetic: "/ˈprəʊses/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "proportion", level: "B2", translation: "สัดส่วน", phonetic: "/prəˈpɔːʃn/", posEn: "n.", posTh: "นาม" },
  { word: "prospect", level: "B2", translation: "โอกาส/ความคาดหวัง", phonetic: "/ˈprɒspekt/", posEn: "n.", posTh: "นาม" },
  { word: "pursue", level: "B2", translation: "ติดตาม/ไล่ตาม", phonetic: "/pəˈsjuː/", posEn: "v.", posTh: "กริยา" },
  { word: "quote", level: "B2", translation: "อ้างอิง/ราคาเสนอ", phonetic: "/kwəʊt/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "reaction", level: "B2", translation: "ปฏิกิริยา/การตอบสนอง", phonetic: "/riˈækʃn/", posEn: "n.", posTh: "นาม" },
  { word: "recognition", level: "B2", translation: "การยอมรับ/การจำได้", phonetic: "/ˌrekəɡˈnɪʃn/", posEn: "n.", posTh: "นาม" },
  { word: "recommend", level: "B2", translation: "แนะนำ", phonetic: "/ˌrekəˈmend/", posEn: "v.", posTh: "กริยา" },
  { word: "recovery", level: "B2", translation: "การฟื้นตัว", phonetic: "/rɪˈkʌvəri/", posEn: "n.", posTh: "นาม" },
  { word: "reduction", level: "B2", translation: "การลดลง", phonetic: "/rɪˈdʌkʃn/", posEn: "n.", posTh: "นาม" },
  { word: "regional", level: "B2", translation: "ระดับภูมิภาค", phonetic: "/ˈriːdʒənl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "register", level: "B2", translation: "ลงทะเบียน", phonetic: "/ˈredʒɪstə(r)/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "regulation", level: "B2", translation: "กฎข้อบังคับ", phonetic: "/ˌreɡjuˈleɪʃn/", posEn: "n.", posTh: "นาม" },
  { word: "relevant", level: "B2", translation: "ที่เกี่ยวข้อง", phonetic: "/ˈreləvənt/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "reliable", level: "B2", translation: "ที่เชื่อถือได้", phonetic: "/rɪˈlaɪəbl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "requirement", level: "B2", translation: "ข้อกำหนด/ความต้องการ", phonetic: "/rɪˈkwaɪəmənt/", posEn: "n.", posTh: "นาม" },
  { word: "research", level: "B2", translation: "การวิจัย/ค้นคว้า", phonetic: "/rɪˈsɜːtʃ/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "resource", level: "B2", translation: "ทรัพยากร", phonetic: "/rɪˈsɔːs/", posEn: "n.", posTh: "นาม" },
  { word: "respond", level: "B2", translation: "ตอบสนอง", phonetic: "/rɪˈspɒnd/", posEn: "v.", posTh: "กริยา" },
  { word: "retain", level: "B2", translation: "เก็บรักษาไว้/จำไว้", phonetic: "/rɪˈteɪn/", posEn: "v.", posTh: "กริยา" },
  { word: "reveal", level: "B2", translation: "เปิดเผย", phonetic: "/rɪˈviːl/", posEn: "v.", posTh: "กริยา" },
  { word: "revenue", level: "B2", translation: "รายได้", phonetic: "/ˈrevənjuː/", posEn: "n.", posTh: "นาม" },
  { word: "role", level: "B2", translation: "บทบาท", phonetic: "/rəʊl/", posEn: "n.", posTh: "นาม" },
  { word: "sector", level: "B2", translation: "ภาคส่วน", phonetic: "/ˈsektə(r)/", posEn: "n.", posTh: "นาม" },
  { word: "secure", level: "B2", translation: "ปลอดภัย/ทำให้ปลอดภัย", phonetic: "/sɪˈkjʊə(r)/", posEn: "v., adj.", posTh: "กริยา/คุณศัพท์" },
  { word: "sequence", level: "B2", translation: "ลำดับ", phonetic: "/ˈsiːkwəns/", posEn: "n.", posTh: "นาม" },
  { word: "shift", level: "B2", translation: "การเปลี่ยน/กะทำงาน", phonetic: "/ʃɪft/", posEn: "v., n.", posTh: "กริยา/นาม" },
  { word: "significant", level: "B2", translation: "ที่มีนัยสำคัญ", phonetic: "/sɪɡˈnɪfɪkənt/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "similar", level: "B2", translation: "คล้ายกัน", phonetic: "/ˈsɪmələ(r)/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "status", level: "B2", translation: "สถานะ", phonetic: "/ˈsteɪtəs/", posEn: "n.", posTh: "นาม" },
  { word: "strategic", level: "B2", translation: "ในเชิงกลยุทธ์", phonetic: "/strəˈtiːdʒɪk/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "strategy", level: "B2", translation: "กลยุทธ์", phonetic: "/ˈstrætədʒi/", posEn: "n.", posTh: "นาม" },
  { word: "structure", level: "B2", translation: "โครงสร้าง", phonetic: "/ˈstrʌktʃə(r)/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "subsequent", level: "B2", translation: "ที่ตามมาภายหลัง", phonetic: "/ˈsʌbsɪkwənt/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "sustainable", level: "B2", translation: "ที่ยั่งยืน", phonetic: "/səˈsteɪnəbl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "target", level: "B2", translation: "เป้าหมาย", phonetic: "/ˈtɑːɡɪt/", posEn: "n., v.", posTh: "นาม/กริยา" },
  { word: "technical", level: "B2", translation: "ในทางเทคนิค", phonetic: "/ˈteknɪkl/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "theory", level: "B2", translation: "ทฤษฎี", phonetic: "/ˈθɪəri/", posEn: "n.", posTh: "นาม" },
  { word: "transform", level: "B2", translation: "เปลี่ยนโฉม/แปรรูป", phonetic: "/trænsˈfɔːm/", posEn: "v.", posTh: "กริยา" },
  { word: "trend", level: "B2", translation: "แนวโน้ม", phonetic: "/trend/", posEn: "n.", posTh: "นาม" },
  { word: "unique", level: "B2", translation: "ที่เป็นเอกลักษณ์", phonetic: "/juˈniːk/", posEn: "adj.", posTh: "คุณศัพท์" },
  { word: "variable", level: "B2", translation: "ตัวแปร/ที่เปลี่ยนแปลงได้", phonetic: "/ˈveəriəbl/", posEn: "n., adj.", posTh: "นาม/คุณศัพท์" },
  { word: "volume", level: "B2", translation: "ปริมาตร/ระดับเสียง", phonetic: "/ˈvɒljuːm/", posEn: "n.", posTh: "นาม" },
];
